### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by adriancole** [openzipkin/Zipkin.Tracer#10]
@Horusiath looks like you've picked up a user :) Do you expect to continue this project? If not, it might be a good idea to move it to OpenZipkin, have OpenZipkin fork it, or add @rogeralsing as a collaborator.

There are some changes that should be made to make this more supportable moving forward, and it would be nice for someone to re-use your efforts. Let us know what you are thinking.

**Comment by Horusiath** [comment]
I think, we can move this project to OpenZipkin.

**Comment by adriancole** [comment]
Sounds good! easiest way would be to add me as an admin of this, then I can transfer as I have admin on OpenZipkin org.

**Comment by adriancole** [comment]
sweet. you can remove me from the old org if you like
