### ISSUE TITLE
Rename repo to zipkin-csharp?

### ISSUE THREAD

**Issue by adriancole** [openzipkin/Zipkin.Tracer#11]
It would be nice to have a good base .net tracer vs a lot of one-off ones. That will allow projects like  https://github.com/mdsol/Medidata.ZipkinTracerModule and https://logary.github.io/targets/zipkin/ to layer on a sound foundation. Plus, it makes maintenance and api drift tracking easier.

This seems to be the least dependencies basic tracer, but it is probably hard for anyone to know what it is by the repo name. What if we renamed this to zipkin-csharp?

cc @jcarres-mdsol @haf

**Comment by jcarres-mdsol** [comment]
I'm in for a rename. @bvillanueva-mdsol  ?

**Comment by adriancole** [comment]
no opposition, so doing it!

**Comment by haf** [comment]
Makes sense. `Logary.Zipkin` is this repo, nuget-ified, because this wasn't... I'd appreciate any help in making Logary support ZipKin out of the box btw. :)

**Comment by adriancole** [comment]
@haf opened https://github.com/openzipkin/zipkin-csharp/issues/12 to track nuget-ification cc @abesto

**Comment by johnberzy-bazinga** [comment]
Sorry I know I'm a little late on this. Would something like zipkin-dotnet be more appropriate?

**Comment by adriancole** [comment]
hehe nothing gets feedback like renaming something :)

I don't mind. I just noticed that the csharp convention was used in
opentracing easy to rename it to something else (though we should probably
stick to whatever that is)

On Wed, Sep 21, 2016 at 4:03 PM, johnberzy-bazinga <notifications@github.com

**Comment by haf** [comment]
I wouldn't mind making Logary.Zipkin the top-level project here and have people contribute to Logary as the main client. Of course, Logary is primarily F#, but I don't mind depending on things C#, like here.

**Comment by adriancole** [comment]
@haf one of the initial motivations for this repo was to have a minimal library (conscious of dependencies). For example, the https://github.com/mdsol/Medidata.ZipkinTracerModule had some framework tie-ins that weren't desirable as a substrate for all types of projects.

Do you think that Logary.Zipkin's code would address that? ex. it probably has dependencies on Logary?

**Comment by adriancole** [comment]
@haf ah ok. I didn't realize it was the same codebase! So what would the next steps be then?

**Comment by haf** [comment]
I'm looking for help to make it all come together for .Net as it's too much work for a single person. It depends on what is offered, but generally, I after creating a sample that ties [Logary's examples](https://github.com/logary/logary/blob/master/examples/Logary.ConsoleApp/Program.fs) together with [Suave.io](https://suave.io/) with [F# on Kubernetes](https://github.com/haf/kubernetes-hello-fsharp) with [Grafana](http://grafana.org/) and [Infrastructure monitoring](https://github.com/kubernetes/heapster/issues/1303)

**Comment by adriancole** [comment]
interesting.. if things work similar to other projects I've seen, sample
projects end up being good in separate repos. ex in zipkin's gitter, we
routinely get asked about very straightforward how-tos
https://gitter.im/openzipkin/zipkin

towards that end, we have some demos that look the same, which make it
easier for zipkin to help support.

ex something brutally simple, which shows how to use a library (and
facilitates copy/paste starter folks)

https://github.com/openzipkin/jaeger-jersey-example

then less accessible, but more robust samples like you mentioned

ex spring has a separate repo for its bigger demo
https://github.com/spring-cloud-samples/brewery

In this repo, we'd want to focus on the code itself, ex. those libraries
underpinning integrations such as the ones you mentioned. It would be more
than reasonable, and somewhat normal to host libraries that bind to common
things like suave or logary here, along with the core library.

ex zipkin js has many (but not all) integrations hosted in its core repo
https://github.com/openzipkin/zipkin-js/tree/master/packages

Things I thought of from what you said are...

* you probably should be a collaborator on this repo! let me know if you
are up to it
* there are a couple who've worked on this repo, and hopefully that
increases
* we can create extra repos for simple and "wow me" projects, as well
market them through twitter, the user list and any conferences
* we should probably name the repo zipkin-dotnet as seems there will be
different languages here if we host libraries that are in f#

>
back at you!

**Comment by adriancole** [comment]
FYI all I noticed that this repo hasn't had any code activity. Meanwhile another repo opened up and has started doing releases.

https://github.com/clearctvm/zipkin.net

Tracer libraries are only valuable when they are alive. Does anyone plan to work on this repo?

**Comment by haf** [comment]
Logary Zipkin is releasing, albeit not changing that much right now.

Like I said, help with getting the samples up and running would be great. I've been toiling away at the metrics abstractions that will allow you to annotate spans with metrics/gauges/derived measurements in this PR https://github.com/logary/logary/pull/182 and I'm making my way towards correlating events to send to zipkin using this library. Hammet is a good coder, but can be very opinionated and has a very special flavour of C# that he writes (that I don't agree completely with).

**Comment by adriancole** [comment]
@haf thanks for the feedback. Hammet mentioned that the style is opinionated, which has the pros and cons of being opinionated I guess. That said an alive, opinionated repo is better than a dead one. Probably best thing to do is wait another couple weeks to see if this repo comes back to life or not.

**Comment by jcarres-mdsol** [comment]
That would be the third repo with a C# tracer implementation.
Is there anything we can do at https://github.com/mdsol/Medidata.ZipkinTracerModule to merge it with this or other repo?

**Comment by adriancole** [comment]
> That would be the third repo with a C# tracer implementation.
> Is there anything we can do at https://github.com/mdsol/Medidata.ZipkinTracerModule to merge it with this or other repo?

I feel you. My only concern is that the code is maintained. I believe
the motivation for this repo was initially that ZipkinTracerModule had
some instrumentation bias (ex the tracer wasn't explicitly separate
from the middleware). This was also the case with pyramid_python until
recent work to decouple it (py_zipkin).

Since ZipkinTracerModule has had persistent contributions over time,
it certainly would seem sensible to leverage. My guess is that it
would be a matter of decoupling and perhaps style (both of which I'm
not an authority on as I've no experience in .net)

**Comment by jcarres-mdsol** [comment]
I've talked with the developers of the https://github.com/mdsol/Medidata.ZipkinTracerModule and they say that in theory it would be easy to take the middleware out but in practice it's one of those things than once you put yourself into it, end up rewriting the thing.
And giving that using middlewares is supposed to be the way to go for cleaner code, I think there is not much interest around here to break the two pieces apart.
@bvillanueva-mdsol  @lschreck-mdsol  thoughts?

**Comment by haf** [comment]
I expect things to happen over a couple of months rather than a couple of weeks. The OSS liquidity in F#/C# is low compared to Ruby/Python/JS and even Java.

**Comment by adriancole** [comment]
>
> I expect things to happen over a couple of months rather than a couple of
> weeks. The OSS liquidity in F#/C# is low compared to Ruby/Python/JS and
> even Java.
>
ah ok. Thanks for setting expectations!

**Comment by Horusiath** [comment]
@jcarres-mdsol the main reason why I've created this plugin is because of at that time the Medidata's one was the only one available, and tightly coupled to Owin middleware. This plugin was created to be minimal, non-opinionated and available to be used no matter what programming style you wish to use. I wanted it to be embedded into end user scenarios (such as logary i.e.).

Unfortunately I'm heavily out of time to provide constant support for it.

**Comment by lschreck-mdsol** [comment]
> they say that in theory it would be easy to take the middleware out but in practice it's one of those things than once you put yourself into it, end up rewriting the thing.

@jcarres-mdsol You are right about this, we could do a fast and dirty breakout now (as we are not able to invest much time into this project currently) but I feel that this would not reach a minimal quality and stability level.

Also, based on my refactoring/open sourcing experience with our [MAuth](https://github.com/mdsol/mauth-client-dotnet) end of the day a full rewrite would need to be necessary.

Also,
> And giving that using middlewares is supposed to be the way to go for cleaner code, I think there is not much interest around here to break the two pieces apart.

That is true partly, but unfortunately on the .NET part our problem is that we've coupled the library to a particular middleware implementation (namely Microsoft.Owin / Katana). So for example .NET Core has its own OWIN middleware infrastructure implementation under a new namespace which cannot be used with the ZipkinTracerModule, because it is tightly coupled to the old implementation.

**Comment by jcarres-mdsol** [comment]
@lschreck-mdsol At least we should support Core. Core is cool, be like Core
